### PR TITLE
[#1166] Fix page_count

### LINKED ISSUE #1166: Update page count of records with page count 0
Basically more records are affected by https://github.com/galterlibrary/digital-repository/issues/1088 .

Couple of things to check:
- Can page count be changed in DH and does it reflect in the `page_count` used for export?
- Could we run a script to find all instances in DH? (we already know a couple records in the NUCATs grants repository are affected)?
-

### PR DESCRIPTION
**Pull request by sharpattack**
Using provided list of records, use `pdfinfo` to retreive correct page count for associated files. closes #1166

### CODE REVIEW

File: lib/scripts/1166_fix_page_count.rb [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+data.each do |row|
+  begin
+    generic_file = GenericFile.find(row["dh_id"])
+  rescue ActiveFedora::ObjectNotFoundError
+    puts "Could not find record for #{row["dh_id"]}"
+    next
+  end
+
+  begin
+    generic_file.page_count = [`pdfinfo #{row["filepath"]} | grep "Pages" | cut -d":" -f 2 | sed 's/ //g'`]
```
Comment (sharpattack) [inline lib/scripts/1166_fix_page_count.rb:19]: `pdfinfo` is missing from the production and staging servers. Oddly, I found an old script that uses `pdfinfo` the same way, but must have been removed at some point. IT ticket to install package is opened. Needs a quick test by hand when `pdfinfo` is available.

File: lib/scripts/filepaths_of_records_w_invalid_page_count.csv [hunk 2]
```diff
@@ -0,0 +1,97 @@
+dh_id,filepath
+4e9c1cbe-28b8-4221-b6ce-3a4282b81b9f,/var/www/apps/galter_hydra_jetty/shared/fcrepo4-data/fcrepo.binary.directory/e3/78/b6/e378b63d7dca2d49af6cb6dc72e431404de70b79
```
Comment (sharpattack) [inline lib/scripts/filepaths_of_records_w_invalid_page_count.csv:2]: This one is on staging only, to be tested before production.

**Review by Meowcenary — APPROVED** [review]

**Review by mattbaumann1 — APPROVED** [review]

**Review by mattbaumann1 — APPROVED** [review]
