### PR TITLE
[#1068] 2022-08-17 Repo Export Bug Fixes

### LINKED ISSUE #1068: 2022-08-17 Repo Export Bug Fixes
- InveinoRdmRecordConverter#build_creator_contributor_json has a logic issue where it expects have a user object to check for an orcid id, but the value is nil. Add safe navigation operator to this
- Seemingly related to the above, there's an error that appears a few times where `.merge!({...})` is being called on a nil value. The most obvious place to check is build_creator_contributor_json, but this issue might be a result of a nil value being returned from here to a different function
- ... more to come I'm sure

### PR DESCRIPTION
**Pull request by Meowcenary**
Previous refactors introduced a bug where a User object is expected, but
nil values were being referenced. Also in previous refactors creatibutor
json was updated to have identifiers under the key "person_or_org". Ruby
hashes can be constructed with strings as key, but must be looked up
with symbols. closes #1068

### CODE REVIEW

File: app/models/invenio_rdm_record_converter.rb [hunk 1]
```diff
@@ -247,9 +255,9 @@ def build_creator_contributor_json(creator)
         }
       }
 
-      if dh_user.orcid.present?
+      if dh_user&.orcid.present?
```
Comment (fenekku) [inline app/models/invenio_rdm_record_converter.rb:258]: My bad with that `|| creator.include?(",")` refactor.

File: app/models/invenio_rdm_record_converter.rb [hunk 2]
```diff
@@ -247,9 +255,9 @@ def build_creator_contributor_json(creator)
...
         identifiers = [{"scheme": "orcid", "identifier": dh_user.orcid.split('/').pop}]
-        creatibutor_json["person_or_org"].merge!({"identifiers": identifiers})
+        creatibutor_json[:person_or_org].merge!({"identifiers": identifiers})
```
Comment (fenekku) [inline app/models/invenio_rdm_record_converter.rb:260]: yeah pretty awful

**Review by fenekku — APPROVED** [review]
Thanks for fixing those right away @Meowcenary

File: app/models/invenio_rdm_record_converter.rb [hunk 3]
```diff
@@ -239,6 +239,14 @@ def build_creator_contributor_json(creator)
       }
     # Personal record with user in database OR is a person's formal name
     elsif dh_user.present? || creator.include?(",")
+      creatibutor_json = {
+        "person_or_org": {
+          "given_name": "given_name",
+          "family_name": "family_name",
+          "type": "personal"
+        }
+      }
```
Comment (sharpattack) [inline app/models/invenio_rdm_record_converter.rb:248]: Is this supposed to be in here?

File: app/models/invenio_rdm_record_converter.rb (hunk 1 above)
Comment (Meowcenary) [reply app/models/invenio_rdm_record_converter.rb:258]: Nah, that's my bad for not noticing lol. I wrote this myself after all.

File: app/models/invenio_rdm_record_converter.rb (hunk 3 above)
Comment (Meowcenary) [reply app/models/invenio_rdm_record_converter.rb:248]: omg no :(

Comment (Meowcenary) [reply app/models/invenio_rdm_record_converter.rb:248]: ahhhh thanks @sharpattack  - this would have been disastrous

Comment (sharpattack) [reply app/models/invenio_rdm_record_converter.rb:248]: I see this was merged. Did this change end up being needed?
