### PR TITLE
[#29] Fix Publication Date Format

### LINKED ISSUE #29: Figure out how to do groups
No user defined groups in ldap AFAICT

### PR DESCRIPTION
**Pull request by Meowcenary**
Refactor publication date formatting to use strftime instead of with
string interpolation. Zero pad month and day. closes #29

### CODE REVIEW

File: app/models/invenio_rdm_record_converter.rb [hunk 1]
```diff
@@ -130,7 +130,7 @@ def invenio_metadata(gf)
       "description": gf.description.first,
       "additional_descriptions": additional_descriptions(gf.description),
       "publisher": gf.publisher.shift,
-      "publication_date": "#{gf.date_uploaded.year}-#{gf.date_uploaded.month}-#{gf.date_uploaded.day}",
```
Comment (Meowcenary) [inline app/models/invenio_rdm_record_converter.rb:133]: I'm not sure why I did this in the first place. I'm going to run a test export to make sure that this wasn't intentional.

File: app/models/invenio_rdm_record_converter.rb [hunk 2]
```diff
@@ -285,4 +285,8 @@ def version(content)
 
     "v#{version_number}.0.0"
   end
+
+  def format_publication_date(publication_date)
+    publication_date.strftime("%Y-%m-%d")
```
Comment (Meowcenary) [inline app/models/invenio_rdm_record_converter.rb:290]: `%m` is zero padded month and `%d` is zero padded day.

**Comment by Meowcenary** [comment]
Just finished a test run on staging, seems like it went okay.

File: app/models/invenio_rdm_record_converter.rb [hunk 3]
```diff
@@ -130,7 +130,7 @@ def invenio_metadata(gf)
       "description": gf.description.first,
       "additional_descriptions": additional_descriptions(gf.description),
       "publisher": gf.publisher.shift,
-      "publication_date": "#{gf.date_uploaded.year}-#{gf.date_uploaded.month}-#{gf.date_uploaded.day}",
+      "publication_date": format_publication_date(gf.date_uploaded),
```
Comment (fenekku) [inline app/models/invenio_rdm_record_converter.rb:133]: For the `publication_date`, I thought we wanted to use `gf.date_created` first (or something like it) and then fall back on `gf.date_uploaded`. For instance https://digitalhub.northwestern.edu/files/7bcdc672-2525-4a80-b0a1-143de6cddbc6 was uploaded in our time but created in 1893-03-07 . In the following box correspondence document https://northwestern.app.box.com/file/684887467855?s=1e1ogwnz4vrh7upmrlfuf3nk4vw1ap64 publication_date in InvenioRDM is associated with date created in Digitalhub.

Honestly, I still have some issues figuring out where these box files are, which ones are the right ones and whether or not we encountered additional information that changed things... That box link was right last time I checked with Sara though in December 2020.

**Review by fenekku — COMMENTED** [review]
We should revise the source of publication_date.

**Comment by Meowcenary** [comment]
After discussion on Slack we've settled on the following for this field:

- we use date created from DH if it's there
- if it's not we fallback to date uploaded
- when librarians check migrated records, they can tell us if something isn't right

Hopefully we will not revisit this, but if we do now we will have a point of reference

File: app/models/invenio_rdm_record_converter.rb [hunk 4]
```diff
@@ -286,4 +290,75 @@ def version(content)
 
     "v#{version_number}.0.0"
   end
+
+  def format_publication_date(publication_date)
+    normalize_date(publication_date)
+  end
+
+  def normalize_date(date_string)
```
Comment (Meowcenary) [inline app/models/invenio_rdm_record_converter.rb:298]: This is a beast of a function and, as you can probably tell, it's brittle. This is the best I can come up with given how many cases we need to cover. I don't see a reason to refactor right now since this is probably only going to be used for the migration.

File: spec/models/invenio_rdm_record_converter_spec.rb [hunk 5]
```diff
@@ -381,4 +381,117 @@
...
+    context "normalizes date with ca or similar text" do
+      let(:circa_date){ "ca. 1900" }
+      let(:formatted_circa_date){ "1900" }
+
+      it "normalizes date" do
+        expect(invenio_rdm_record_converter.send(:normalize_date, circa_date)).to eq(formatted_circa_date)
+      end
+    end
+
+    # it "normalizes date with seasonal specifier" do
```
Comment (Meowcenary) [inline spec/models/invenio_rdm_record_converter_spec.rb:430]: I'm going to email the DWIG group and see what we should do here.

**Comment by Meowcenary** [comment]
At long last this is ready for review again! @fenekku @sharpattack

File: app/models/invenio_rdm_record_converter.rb [hunk 6]
```diff
@@ -286,4 +290,75 @@ def version(content)
...
+    split_date = date_string.split(/[-,\/ ]/).map(&:downcase)
+    month_names = (split_date & MONTHNAMES)
+    abbr_month_names = (split_date & ABBR_MONTHNAMES)
+
+    # blank and unddated
```
Comment (Meowcenary) [inline app/models/invenio_rdm_record_converter.rb:303]: each of these branches could potentially be it's own function, but I decided to just use these comments while I worked through it. Originally my intention was to go back and refactor, but I really don't think that's worth the time given how long this took me to complete.

**Review by sharpattack — COMMENTED** [review]
Thanks for all the tests. They were quite extensive, and makes me more confident in the `#normalize_date` method. Just a couple small questions, but overall great work.

File: app/models/invenio_rdm_record_converter.rb [hunk 7]
```diff
@@ -131,11 +135,11 @@ def invenio_metadata(gf)
       "description": gf.description.first,
       "additional_descriptions": additional_descriptions(gf.description),
       "publisher": gf.publisher.shift,
-      "publication_date": "#{gf.date_uploaded.year}-#{gf.date_uploaded.month}-#{gf.date_uploaded.day}",
+      "publication_date": format_publication_date(gf.date_created.shift || gf.date_uploaded.shift),
       "subjects": SUBJECT_SCHEMES.map{ |subject_type| subjects_for_scheme(gf.send(subject_type), subject_type) }.flatten,
       "contributors": contributors(gf.contributor),
       "dates": gf.date_created.map{ |date| {"date": date, "type": "other", "description": "When the item was originally created."} },
-      "languages": gf.language.any?{ |lang| lang.downcase == ENGLISH} ? ["eng"] : "",
+      "languages": gf.language.any?{ |lang| lang.downcase == ENGLISH } ? ["eng"] : "",
```
Comment (fenekku) [inline app/models/invenio_rdm_record_converter.rb:142]: probably best to ignore that whitespace change to sidestep a conflict with the other languags PR

**Review by fenekku — APPROVED** [review]
Double check @sharpattack comments . Otherwise good, thanks for going through this. Free text is chaotic.

File: app/models/invenio_rdm_record_converter.rb (hunk 7 above)
Comment (Meowcenary) [reply app/models/invenio_rdm_record_converter.rb:142]: That's a good point. I'll remove that.

File: app/models/invenio_rdm_record_converter.rb [hunk 8]
```diff
@@ -286,4 +290,75 @@ def version(content)
 
     "v#{version_number}.0.0"
   end
+
+  def format_publication_date(publication_date)
+    normalize_date(publication_date)
+  end
+
+  def normalize_date(date_string)
+    split_date = date_string.split(/[-,\/ ]/).map(&:downcase)
```
[the remark this answers is not in the document]
Comment (Meowcenary) [reply app/models/invenio_rdm_record_converter.rb:299]: It will split on -, /, comma, or blank space.

File: spec/models/invenio_rdm_record_converter_spec.rb [hunk 9]
```diff
@@ -381,4 +381,108 @@
...
+
+      it "normalizes date" do
+        expect(invenio_rdm_record_converter.send(:normalize_date, circa_date)).to eq(formatted_circa_date)
+      end
+    end
+
+    context "date with month name or abbreviation" do
+      let(:january_abr_month_name_date){ "January 12, 2020" }
+      let(:march_abr_month_name_date){ "MARCH 2020" }
+      let(:november_abr_month_name_date){ "november 15, 1900" }
```
[the remark this answers is not in the document]
Comment (Meowcenary) [reply spec/models/invenio_rdm_record_converter_spec.rb:433]: haha yeah. I was doing a lot of copy and pasting.

**Comment by Meowcenary** [comment]
Going to rebase and merge this. It keeps getting out of date ha.
